package com.decagon.fashionblog.note;

public class Note {

//    TODO: DATABASE: PRODUCTS: ID,NAME,PRICE,LIKES,COMMENTS,FOREIGN KEY OF USER,
//    TODO: DATABASE: USERS: NAME,EMAIL,ID,PASSWORD
//    TODO: PAGINATION

//    TODO: ADMIN: POST PRODUCTS IN VARIOUS CATEGORIES OF DESIGN TO DATABASE - done
//    TODO: ADMIN: GET ALL PRODUCTS IN THE DATABASE - done
//    TODO:ADMIN: GET PICTURES WITH ID(SEARCHING) - done
//    TODO: ADMIN: PUT(UPDATE) PRODUCTS INFORMATION
//    TODO: ADMIN: DELETE PRODUCTS - done

//    TODO: VISITORS: POST COMMENTS OF INDIVIDUAL PRODUCT-- WITH ID - done
//    TODO: VISITORS: LIKES INDIVIDUAL PRODUCTS-- WITH ID

    // TODO: USE USERDTO
}
