package com.decagon.fashionBlog.note;

public class Note {

//    TODO: DATABASE: PRODUCTS: ID,NAME,PRICE,LIKES,COMMENTS,FOREIGN KEY OF USER, - done
//    TODO: DATABASE: USERS: NAME,EMAIL,ID,PASSWORD - done
//    TODO: PAGINATION

//    TODO: ADMIN: ADD POST  - done
//    TODO: ADMIN: GET ALL POSTS IN THE DATABASE - done
//    TODO:ADMIN: GET POST WITH ID(SEARCHING) - done
//    TODO: ADMIN: PUT(UPDATE) POST INFORMATION
//    TODO: ADMIN: DELETE POST - done
//    TODO: ADMIN: DELETE VISITOR - done

//    TODO: VISITORS: COMMENT ON INDIVIDUAL POST-- WITH ID - done
//    TODO: VISITORS: LIKES POST-- WITH ID -done
//
//     TODO: USE USER-DTO - done
//     TODO: LOGIN ENCRYPTION - done
}
